#!/bin/sh

START_ORAYSL="/etc/oray_phddns/oraysl -a 127.0.0.1 -p 16062 -s phsle01.oray.net:6061 -l /var/log/phddns -L oraysl -f /etc/config/phddns -t /etc/config/phddns/init.status -i /tmp/oraysl.pid -u /tmp/oraysl.status -S /etc/config/phddns -d" >/dev/null 2>&1 
START_ORAYNEWPH="/etc/oray_phddns/oraynewph -s 0.0.0.0 -c /var/log/phddns/core.log -p /var/log/phddns -l oraynewph -f /etc/config/phddns -t /etc/config/phddns/init.status -i /tmp/oraynewph.pid -u /tmp/oraynewph.status -x -d" >/dev/null 2>&1 

checkoraysl()
{
        oraysl=`ps | grep "oraysl" | grep -v 'grep' | awk '{print $1}'`
        if [ -z "$oraysl" ]; then
			$START_ORAYSL
		fi
}

checkoraynewph()
{
        oraynewph=`ps  | grep "oraynewph" | grep -v 'grep' | awk '{print $1}'`
        if [ -z "$oraynewph" ]; then
			$START_ORAYNEWPH
		fi
}

while true
        do 
        checkoraysl  
        checkoraynewph  
        sleep 3
        done

