#!/bin/sh

request_handle()
{
	. $(dirname $0)/get_path
	local init_file="$(get_path)/init.status"
	local config_file="$(get_path)/PhMain.ini"
	
	if [ -f $init_file ]; then
		rm $init_file
	fi	
	if [ -f $config_file ]; then
		rm $config_file
	fi
	
	echo "result_code:0"

	local ORAYSL=`pidof oraysl`
	local ORAYNEWPH=`pidof oraynewph`

	{
		sleep 1 >/dev/null 2>&1
		kill $ORAYNEWPH >/dev/null 2>&1
	} &
	
	return 0
}

case $1 in
	request_handle)
		request_handle "$2"
		;;
	*)
		;;
esac

